### ISSUE TITLE
Support multiple groups

### ISSUE THREAD

**Issue by alcesleo** [eval/envied#15]
Hey! Great gem, this has been really helpful for us. It would be nice to support multiple groups, like in a Gemfile:

``` ruby
group :staging, :production do
   variable :API_URL
end
```

**Comment by nfm** [comment]
+1 :smile: 

Just wanted this too and saw there's already a PR for this. Looks good to me - any chance we can get this merged?

**Comment by jandudulski** [comment]
Yes please! :+1:

**Comment by mkarbowiak** [comment]
:+1:

**Comment by mjonas87** [comment]
:+1:

**Comment by alcesleo** [comment]
A lot of people seem to want this, my PR #16 has been open forever - if you want this feature right away you can use my fork directly until it finally gets merged:

```ruby
# Gemfile
gem "envied", github: "alcesleo/envied", branch: "feature/multiple-groups"
```

**Comment by antonversal** [comment]
:+1:
