### ISSUE TITLE
envied extract doesn't find interpolated ENV variables

### ISSUE THREAD

**Issue by nfm** [eval/envied#21]
Running `envied extract` doesn't find places where I've used ENV that are within an interpolated string. It looks like this is because `#capture_variables` is treating those lines as comments by splitting on the '#' character (https://github.com/eval/envied/blob/cdaf3f1fdb2d932d6aa7ef3df1473f0e3af4c505/lib/envied/env_var_extractor.rb#L39).

As a result, `envied extract` doesn't match things like:

```
redirect_to "#{SOME_CONSTANT_URL}/?secret_key=#{ENV['SOME_SECRET_KEY']}"
link_to "Hi, #{current_user.name}", home_url(secret: ENV['SECRET'])
```

It hits the '#' character, and assumes the rest of the line is a comment, and doesn't look for 'ENV' there.

I'd favour removing the comment handling entirely, as any comments that reference `ENV` should probably be updated to `ENVied` too, if the code is being updated from `ENV` to `ENVied`.

**Comment by javierjulio** [comment]
Agreed. It should function like any search where any matching results should come up and let you decide whether to deal with them or not. But even if it didn't match against commented code it would unintentionally leave interpolated code which isn't good. We shouldn't make to many cases around this, instead should just stick to find `ENV[]` or `ENV.fetch` anywhere it can.

**Comment by javierjulio** [comment]
I've address this in master in commit fa828c1c45ec722e6e6151931ad6d41717842bbb
