### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by supercodepoet** [eval/envied#27]
Is this gem going to update its deps to have Rails 5 support?

**Comment by supercodepoet** [comment]
What would you guys need from the community to get this updated?

**Comment by chytreg** [comment]
@supercodepoet Rails 5 comparability has been resolved some time ago in https://github.com/eval/envied/pull/25 but hasn't been merged yet. I'm using this in my apps with success.

**Comment by javierjulio** [comment]
I'm helping out now with Envied. I just released version 0.8.2 which includes Rails 5 support. Let me know how it works out for you!
