### ISSUE TITLE
Feature request: Support float type

### ISSUE THREAD

**Issue by rhys-vdw** [eval/envied#30]
Not sure if this was deliberate, but I've worked around this like so:

Envfile:
```rb
# Use string for float
variable :ORDER_QUEUE_WINDOW_SCALE_RATE, :string, default: 4.0 / 1.hour
```

In use:
```rb
class OrderQueue
  # ...
  WINDOW_SCALE_RATE = EnvHelper.float(:ORDER_QUEUE_WINDOW_SCALE_RATE)
  # ...
end
```

Helper:
```rb
class EnvHelper
  def self.float(name)
    Float(ENVied.send(name))
  end
end
```

In my case this is fine because it's being set on a constant at startup - but in the case where this value was only used after ENVied has done its value verification this would cause a runtime error.

**Comment by javierjulio** [comment]
Curious as to why you did all that. Did not doing `ENVied.ORDER_QUEUE_WINDOW_SCALE_RATE.to_f` work?

**Comment by rhys-vdw** [comment]
> Curious as to why you did all that.

Good point. I guess I thought `EnvHelper.float` would be more involved when I first wrote it.

I could have done `Float(ENVied.ORDER_QUEUE_WINDOW_SCALE_RATE)`. `String#to_f` doesn't raise on invalid input. eg. `"silly".to_f -> 0.0`

**Comment by javierjulio** [comment]
I've added support for a float type in master now. Thanks @rhys-vdw!

**Comment by rhys-vdw** [comment]
Thanks dude.
