### ISSUE TITLE
envied check:heroku does not support multiline environment variables

### ISSUE THREAD

**Issue by jonahwh** [eval/envied#41]
Because Heroku config vars are [split by newlines](https://github.com/eval/envied/blob/master/lib/envied/cli.rb#L105), environment variables containing newlines cause the `envied check:heroku` task to raise an `ArgumentError`.

Perhaps a solution is to support `heroku config --json`, and parse the json instead of supporting the raw `heroku config`

**Comment by javierjulio** [comment]
Yes, parsing JSON would be better in this case if its well supported and continues to be. We'd definitely consider a PR if you are interested in tackling it.
